//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamedaniProject
{
    using HamedaniProject.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerTable
    {
        public int Id { get; set; }

       
        [Required]
        public string Name { get; set; }
        public bool IsSubscribedToNewsLetter { get; set; }
        public Nullable<int> MembershipTypeId { get; set; }

        [Min18YearsValidation]
        public Nullable<System.DateTime> Birthdate { get; set; }
    
        public virtual MembershipTypeTable MembershipTypeTable { get; set; }
    }
}
